#!/bin/bash

# read_char var
read_char() {
  stty -icanon -echo
  eval "$1=\$(dd bs=1 count=1 2>/dev/null)"
  stty icanon echo
}

BUILD_DIR="cmake-build-release"
CODENAME=$(lsb_release -sc)
ARCH=$(dpkg --print-architecture)
#
char=' '
while true
do
  echo -n "Build hamclock for ${CODENAME} ${ARCH} (Y/n)? "
  read_char char
  [[ $char == 'N' || $char == 'n' ]] && exit 0
  [[ $char != 'Y' && $char != 'y' && $char != '\n' ]] && break
done
echo "Building..."
#
cd SourceCode && ./build && cd .. || exit 1
#
rm -rf ${BUILD_DIR} || exit 1
mkdir ${BUILD_DIR} || exit 1
cd ${BUILD_DIR} || exit 1
cmake -DCMAKE_BUILD_TYPE=Release .. || exit 1
make package || exit 1
exit 0
#
case $CODENAME in
    buster)
	echo "buster"
	~/bin/vfrott -n -c buster -s stable hamclock*.deb
	;;
    bullseye)
	echo "bullseye"
	~/bin/vfrott -n -c bullseye -s stable hamclock*.deb
	;;
    bookworm)
        echo "bookworm"
        ~/bin/vfrott -n -c bookworm -s stable hamclock*.deb
        ;;
    nobel)
	echo "jammy"
	~/bin/gemfury hamclock_*.deb
	~/bin/gemfury hamclock-systemd_*.deb
	~/bin/vfrott -n -s stable hamclock*.deb
	;;
    *)
	echo "No package upload for ${CODENAME}."
	exit 1
esac
