#!/bin/bash

for target in "hamclock-web-800x480" "hamclock-web-1600x960" "hamclock-web-2400x1440" "hamclock-web-3200x1920"
do
	echo $target
	(cd ESPHamClock; make clean; make -j 4 $target; mv $target ..) || exit 1
done
cp ESPHamClock/hamclock.png ESPHamClock/hamclock.desktop .
chmod ug+w hamclock.png hamclock.desktop
