#!/bin/bash

# read_char var
read_char() {
  stty -icanon -echo
  eval "$1=\$(dd bs=1 count=1 2>/dev/null)"
  stty icanon echo
}

if test -d ESPHamClock; then
  VERSION_STRING=$(grep -o '".*"' ESPHamClock/version.cpp | sed 's/"//g')
  char=' '
  while true
  do
    echo -n "Existing source directory found with version $VERSION_STRING, download fresh files (Y/n)? "
    read_char char
    [[ $char == 'N' || $char == 'n' ]] && echo && exit 0
    [[ $char == 'Y' || $char == 'y' || $char == "" ]] && break
  done
fi

echo "Downloading..."

rm -f ESPHamClock.tgz
rm -rf ESPHamClock
wget -q https://www.clearskyinstitute.com/ham/HamClock/ESPHamClock.tgz
tar -zxvf ESPHamClock.tgz

rm -f hamclock-1600x960 hamclock-2400x1440 hamclock-3200x1920 hamclock-800x480 hamclock-fb0-1600x960 hamclock-fb0-2400x1440 hamclock-fb0-3200x1920 hamclock-fb0-800x480
